In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [1]:
data = r'https://raw.githubusercontent.com/rafaelpuyau/infinity_school/main/ds/datasets/wines.csv'

In [6]:
df = pd.read_csv(data)

In [7]:
df.head(3)

date   label  vintage   style   country   price  quantity  rate
0  2021-01-04  Wine K     2002   White  Portugal  144.22         9    97
1  2021-03-11  Wine J     1982     Red  Portugal  244.80         3    76
2  2021-10-02  Wine Y     2018  Orange    France   98.83         2    79

In [8]:
df['style'].unique()

array(['White', 'Red', 'Orange', 'Sparkling', 'Rose', 'Sweet'],
      dtype=object)

In [10]:
df['style'].value_counts()

style
White        1710
Rose         1706
Orange       1658
Sweet        1648
Red          1640
Sparkling    1638
Name: count, dtype: int64

In [11]:
df['quantity'].max()

15

In [12]:
df['quantity'].min()

1

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   date      10000 non-null  object 
 1   label     10000 non-null  object 
 2   vintage   10000 non-null  int64  
 3   style     10000 non-null  object 
 4   country   10000 non-null  object 
 5   price     10000 non-null  float64
 6   quantity  10000 non-null  int64  
 7   rate      10000 non-null  int64  
dtypes: float64(1), int64(3), object(4)
memory usage: 625.1+ KB


In [14]:
df['date'] = pd.to_datetime(df['date'])

Atividade 02

Leia a base de dados sobre vinhos, e responda as

seguintes perguntas:

1.Sobre o que se tratam esses dados?

2.Qual é o estilo que mais aparece?

3.Qual é o preço e a etiqueta do(s) vinho(s) mais caro(s)?

4.Qual é o preço e o estilo do(s) vinho(s) mais barato(s)?

In [16]:
df['style'].value_counts(1)

style
White        0.1710
Rose         0.1706
Orange       0.1658
Sweet        0.1648
Red          0.1640
Sparkling    0.1638
Name: proportion, dtype: float64

In [17]:
df['style'].mode()

0    White
Name: style, dtype: object

In [19]:
df[['label', 'price']].sort_values('price', ascending=False).head(1)

label    price
1249  Wine Q  1107.89

In [20]:
df[['style', 'price']].sort_values('price', ascending=True).head(1)

style  price
9256  Sweet  50.01

##Numpy

In [21]:
vetor = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
vetor

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
vetor+3

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [23]:
lista = [x for x in range(1, 11)]
lista


[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [25]:
vetor2 = vetor * vetor
vetor2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [27]:
vetor**3

array([   1,    8,   27,   64,  125,  216,  343,  512,  729, 1000])

In [28]:
np.power(vetor2, 3)

array([      1,      64,     729,    4096,   15625,   46656,  117649,
        262144,  531441, 1000000])

In [29]:
np.sqrt(vetor)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [30]:
vetor**(1/2)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [32]:
np.arange(5, 21, 2)

array([ 5,  7,  9, 11, 13, 15, 17, 19])

In [34]:
np.linspace(0, 10, 5)


array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [42]:
a = np.array(list(range(5,21,5)))
a

array([ 5, 10, 15, 20])

In [43]:
b = np.arange(1, 6, 1)
b

array([1, 2, 3, 4, 5])

##Iloc

In [47]:
df.iloc[0:1001, 2:6]

vintage      style   country   price
0        2002      White  Portugal  144.22
1        1982        Red  Portugal  244.80
2        2018     Orange    France   98.83
3        1989        Red     Spain   59.64
4        2006      White     Spain  187.70
...       ...        ...       ...     ...
996      2020  Sparkling     Italy   50.37
997      2013  Sparkling   Germany  285.28
998      1996       Rose     Chile   55.53
999      1999  Sparkling     Chile  171.81
1000     2007      White   Uruguay  191.26

[1001 rows x 4 columns]

In [48]:
df.sort_values(['vintage', 'price'])

date   label  vintage      style   country   price  quantity  rate
1222 2021-12-27  Wine R     1982  Sparkling   Uruguay   50.39        10    86
9951 2021-01-05  Wine T     1982       Rose   Germany   50.63         3    92
6971 2021-06-14  Wine V     1982      Sweet   Uruguay   52.25         8    92
3287 2021-05-25  Wine W     1982      Sweet       USA   52.47         6    83
5016 2021-03-12  Wine Y     1982     Orange    France   53.73        11    77
...         ...     ...      ...        ...       ...     ...       ...   ...
4866 2021-05-04  Wine J     2021        Red  Portugal  569.77        15    95
1989 2021-05-16  Wine Z     2021     Orange  Portugal  614.78        15    89
44   2021-03-18  Wine P     2021  Sparkling  Portugal  732.71         7    95
3724 2021-11-22  Wine Z     2021     Orange     Chile  759.71         7    89
7807 2021-07-16  Wine T     2021       Rose    Brazil  790.75         2    92

[10000 rows x 8 columns]

##loc

In [50]:
df.loc[(df['style'] == 'Red') & (df['rate'] >=90) & (df['rate'] > 80)]

date   label  vintage style    country   price  quantity  rate
6    2021-11-01  Wine A     2003   Red        USA  464.32         9    99
17   2021-04-22  Wine G     2018   Red        USA  410.45         7    98
27   2021-07-14  Wine E     1983   Red      Chile  306.10        15    99
45   2021-11-06  Wine H     2005   Red    Germany  226.67         3    90
54   2021-08-27  Wine B     1985   Red   Portugal  227.87         9    99
...         ...     ...      ...   ...        ...     ...       ...   ...
9952 2021-10-14  Wine I     2015   Red    Uruguay  246.65         3    99
9956 2021-04-15  Wine F     1989   Red     Brazil   90.48        15    90
9970 2021-06-12  Wine F     2001   Red  Argentina  298.45         3    97
9982 2021-11-03  Wine B     2015   Red      Chile   83.89         3    97
9985 2021-06-18  Wine I     1988   Red      Chile  164.67         6    93

[669 rows x 8 columns]

qual o vinho vermelho em maior quantidade ?

label e safra do vinho laranja de menor nota?

In [58]:
df.loc[(df['style'] == 'Red') & (df['quantity']).max() & (df['country'] == 'USA').sort_values(ascending=True)]

date   label  vintage style country   price  quantity  rate
6    2021-11-01  Wine A     2003   Red     USA  464.32         9    99
17   2021-04-22  Wine G     2018   Red     USA  410.45         7    98
94   2021-08-08  Wine D     2017   Red     USA  405.92        10    92
103  2021-08-08  Wine C     2012   Red     USA  615.06         8    97
206  2021-02-06  Wine E     2014   Red     USA   72.02        15    88
...         ...     ...      ...   ...     ...     ...       ...   ...
9587 2021-12-28  Wine H     2007   Red     USA   71.44         1    78
9681 2021-10-27  Wine A     1985   Red     USA  308.65         3   100
9715 2021-12-29  Wine B     1998   Red     USA  504.59         6    89
9809 2021-11-12  Wine C     1992   Red     USA  199.21        11    86
9810 2021-10-10  Wine G     1982   Red     USA  250.61         9    94

[141 rows x 8 columns]

In [62]:
df.loc[(df["style"] == "Red")].sort_values("quantity", ascending=False)[["label", "style", "quantity"]]

label style  quantity
27    Wine E   Red        15
8270  Wine J   Red        15
8249  Wine J   Red        15
8283  Wine D   Red        15
2607  Wine D   Red        15
...      ...   ...       ...
386   Wine J   Red         1
402   Wine J   Red         1
9777  Wine G   Red         1
225   Wine C   Red         1
9992  Wine F   Red         1

[1640 rows x 3 columns]

In [61]:
df.loc[((df["style"] == "Orange"))].sort_values("rate", ascending=True)[["label", "vintage"]]

label  vintage
491   Wine Y     2007
9663  Wine Z     2016
2239  Wine Z     1990
8132  Wine Y     2002
8008  Wine Y     1989
...      ...      ...
91    Wine Y     1994
9979  Wine Z     1993
9933  Wine Y     2013
360   Wine Y     1995
218   Wine Y     2005

[1658 rows x 2 columns]